# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  commands:
  - asdf global python 3.11.4
  - python3 -m pip install --upgrade --no-cache-dir pip setuptools
  - python3 -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 mkdocs==0.17.3
  - python3 -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
  - python3 -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt #we have to create this file mentiniong all the python libraries with version.

search:
   ignore:
   - 404.html